### ISSUE TITLE
Move and link specs

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/go-square#15]
### Summary

Currently the specs for these packages are still located on the `celestia-app` repo. For coherence, we should either move them here and add appropriate links on `celestia-app` or update the links to the specs in this repo

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
I think we should think about the desired end-state before tackling this issue. One possible end-state that I like:
1. All specs hosted at https://celestiaorg.github.io/celestia-app/
2. The spec for a component lives in the same repo as the code that implements that component

**Comment by cmwaters** [comment]
Yes in my ideal world, all specs are compiled together and hosted in a domain like https://specs.celestia.org with each repo containing the specs that are relevant to them

**Comment by rootulp** [comment]
Agreed but I think the ideal approach may be a bit cumbersome to implement because it would involve syncing the specs from this repo to celestia-app and then publishing. I think the easiest path to close this issue is:

In this repo
1. Update [this link](https://github.com/celestiaorg/go-square/blob/fd78256df076539ef5e13cd271276f058a167d8c/shares/README.md?plain=1#L3) to point to https://celestiaorg.github.io/celestia-app/specs/shares.html
2. Update [this link](https://github.com/celestiaorg/go-square/blob/fd78256df076539ef5e13cd271276f058a167d8c/namespace/README.md?plain=1#L3) to point to  https://celestiaorg.github.io/celestia-app/specs/namespace.html

There aren't READMEs for square, inclusion, or blob.

In celestia-app
1. Update [this link](https://github.com/celestiaorg/celestia-app/blob/e05d105e537f1c34bf5a48586f0d0ac32b51df1b/specs/src/specs/shares.md?plain=1#L115) to point to this repo
2. Update [this link](https://github.com/celestiaorg/celestia-app/blob/e05d105e537f1c34bf5a48586f0d0ac32b51df1b/specs/src/specs/namespace.md?plain=1#L92) to point to this repo.

The specs for https://celestiaorg.github.io/celestia-app/specs/data_square_layout.html#data-square-layout don't appear to link to the implementation that moved so I think that's it.

**Comment by rootulp** [comment]
Closed by PRs mentioned above.
